name: flutter_keyboard_aware_dialog
description: Dialog that moves up automaticly when soft keyboard shows. Contains three variants.
version: 1.0.1
homepage: https://github.com/PegasisForever/flutter_keyboard_aware_dialog

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

